/**
 * Biblioteca de ocasiones del generador de temáticas.
 *
 * Cada arquetipo es una ocasión de regalo (amor, mamá, graduación, mascotas…)
 * con todo lo que el generador necesita para armar una temática completa sin
 * que nadie escriba nada: cómo se detecta, su paleta, la portada, los textos
 * de cada slide y las fotos. Los campos que faltan salen del arquetipo base.
 *
 * Las fotos son de Unsplash (dominio permitido en next.config) y están
 * verificadas: existen y muestran lo que dicen.
 */

export interface ArchetypePalette {
  name: string
  primary: string
  ink: string
  accent: string
  /** Color de la tarjeta en la tienda y tono del texto encima. */
  card: string
  tone: 'light' | 'dark'
}

export interface TriviaQuestion {
  question: string
  options: string[]
  correct: number
  hint: string
}

export interface Archetype {
  id: string
  label: string
  /** Palabras que lo detectan (sin tildes, minúsculas). Se buscan como palabras o prefijos. */
  keywords: string[]
  category: string
  emoji: string
  cover: 'recipient' | 'friends' | 'birthday'
  particles: 'heart' | 'friend' | 'bday-fest' | 'circle' | 'none'
  palettes: ArchetypePalette[]
  /** Fotos de Unsplash (id sin "photo-"): la primera es la de la tarjeta. */
  photos: string[]
  listing: {
    title: string
    subtitle: string
    card: string
    features: string[]
    guideTitle: string
    guideText: string
  }
  copy: {
    coverLabel: string
    senderPrefix: string
    greeting: string
    edition: string
    thought: string
    message: string
    dedicationHeading: string
    dedicationDefault: string
    songCaption: string
    reasonsTitle: string
    reasonsSubtitle: string
    reasons: string[]
    reasonsFinal: [string, string]
    coupons: string[]
    trivia: TriviaQuestion[]
    triviaTitle: string
    fortunes: string[]
    anecdoteTitle: string
    thanksTitle: string
    thanksText: string
    friendsQuote?: string
    birthdayTitle?: string
  }
}

type Partial2<T> = { [K in keyof T]?: T[K] extends object ? Partial<T[K]> : T[K] }
export type ArchetypeSpec = Omit<Archetype, 'listing' | 'copy'> & {
  listing: Partial<Archetype['listing']> & Pick<Archetype['listing'], 'subtitle' | 'card'>
  copy: Partial2<Archetype['copy']>
}

// ── Base: lo que comparte cualquier ocasión ────────────────────────────────

export const BASE_COPY: Archetype['copy'] = {
  coverLabel: 'Este regalo especial es para...',
  senderPrefix: 'Con cariño,',
  greeting: '¡HOLA!',
  edition: 'SPECIAL EDITION',
  thought: 'MOMENTOS',
  message: 'Porque te merecés algo tan especial como vos.',
  dedicationHeading: 'Carta para vos 💌',
  dedicationDefault:
    'Te preparé este regalo para recordarte lo importante que sos. Espero que te saque una sonrisa.',
  songCaption: 'eligió esta canción pensando en vos.',
  reasonsTitle: '10 Razones',
  reasonsSubtitle: 'Para recordarte lo especial que sos...',
  reasons: [
    'Por cómo iluminás cualquier lugar.',
    'Por tu forma de escuchar.',
    'Porque siempre estás.',
    'Por tu risa contagiosa.',
    'Por todo lo que compartimos.',
    'Porque sos auténtico/a.',
    'Por tu generosidad.',
    'Por los recuerdos que tenemos.',
    'Por los que vamos a crear.',
    'Simplemente, porque sos vos.',
  ],
  reasonsFinal: ['¡Y un millón más! ✨', 'Gracias por existir.'],
  coupons: [
    'Salida Especial',
    'Comida Favorita',
    'Tarde de Mimos',
    'Plan Sorpresa',
    'Día Libre',
    'Película a Elección',
    'Deseo Cumplido',
    'Comodín',
  ],
  triviaTitle: '¡Desafío Boxie!',
  trivia: [
    {
      question: '¿Cuál es el regalo que más se recuerda?',
      options: ['El más caro', 'El más grande', 'El que emociona', 'El que llega primero'],
      correct: 3,
      hint: 'No se mide en plata 💝',
    },
    {
      question: '¿Cuántas veces podés abrir esta Boxie?',
      options: ['Una sola vez', 'Dos veces', 'Todas las que quieras', 'Ninguna'],
      correct: 3,
      hint: 'Es tuya para siempre (bueno, casi) 😉',
    },
    {
      question: '¿Qué es lo más lindo de un regalo sorpresa?',
      options: ['El envoltorio', 'La cara al abrirlo', 'El ticket de cambio', 'La caja'],
      correct: 2,
      hint: 'Seguro la estás poniendo ahora 😄',
    },
  ],
  fortunes: [
    'Lo que viene es todavía mejor de lo que imaginás.',
    'Alguien piensa en vos más seguido de lo que creés.',
    'Tu energía abre puertas: seguí siendo así.',
    'Se acerca un momento que vas a recordar siempre.',
    'Lo que sembraste con cariño está por florecer.',
  ],
  anecdoteTitle: 'Momento Inolvidable',
  thanksTitle: 'GRACIAS',
  thanksText: 'Por ser parte de mi vida.',
}

const ROSE: ArchetypePalette = {
  name: 'Coral Boxie',
  primary: '#F44E63',
  ink: '#2A2433',
  accent: '#FFD700',
  card: '#F44E63',
  tone: 'light',
}

// ── Arquetipos ─────────────────────────────────────────────────────────────

export const ARCHETYPE_SPECS: ArchetypeSpec[] = [
  {
    id: 'amor',
    label: 'Amor y pareja',
    keywords: [
      'amor',
      'pareja',
      'novio',
      'novia',
      'aniversario',
      'enamorad',
      'valentin',
      'esposo',
      'esposa',
      'mesiversario',
      'te amo',
      'romant',
      '=cita',
      'marido',
    ],
    category: 'Amor',
    emoji: '💘',
    cover: 'recipient',
    particles: 'heart',
    palettes: [
      ROSE,
      {
        name: 'Rojo pasión',
        primary: '#E0314B',
        ink: '#2B1B24',
        accent: '#FFC857',
        card: '#E0314B',
        tone: 'light',
      },
      {
        name: 'Rosa atardecer',
        primary: '#F2789F',
        ink: '#3A2233',
        accent: '#FFE3A3',
        card: '#F9C5D5',
        tone: 'dark',
      },
    ],
    photos: [
      '1518199266791-5375a83190b7',
      '1529619768328-e37af76c6fe5',
      '1516589178581-6cd7833ae3b2',
    ],
    listing: {
      title: 'Boxie para',
      subtitle: 'El regalo digital perfecto para celebrar su amor.',
      card: 'Un regalo lleno de amor para celebrar su historia juntos.',
      guideTitle: 'Para Enamorar',
      guideText: 'Ideal para aniversarios, mesiversarios o simplemente decir "te amo".',
    },
    copy: {
      senderPrefix: 'Con amor,',
      edition: 'LOVE EDITION',
      thought: 'SENTIMIENTOS',
      message: 'Porque sos mi persona favorita.',
      songCaption: 'siempre que se acuerda de vos, piensa en esta canción.',
      reasons: [
        'Por tu forma de mirarme.',
        'Por cómo me hacés reír.',
        'Porque sos mi hogar.',
        'Por tu paciencia infinita.',
        'Porque me apoyás siempre.',
        'Por tus abrazos sanadores.',
        'Por nuestras charlas eternas.',
        'Por cada plan improvisado.',
        'Porque me hacés mejor persona.',
        'Simplemente, porque te amo.',
      ],
      reasonsFinal: ['¡Y un millón más! ✨', 'Te quiero infinito.'],
      coupons: [
        'Cena Romántica',
        'Masaje Relajante',
        'Noche de Cine',
        'Desayuno en la Cama',
        'Escapada',
        'Vale por un Beso',
        'Paseo al Atardecer',
        'Deseo Mágico',
      ],
      trivia: [
        {
          question: '¿Qué flor se asocia con el amor romántico?',
          options: ['Girasol', 'Rosa roja', 'Margarita', 'Tulipán'],
          correct: 2,
          hint: 'Tiene espinas, pero vale la pena 🌹',
        },
        {
          question: '¿En qué ciudad está el famoso "puente de los candados"?',
          options: ['París', 'Roma', 'Madrid', 'Londres'],
          correct: 1,
          hint: 'La ciudad del amor 🗼',
        },
        {
          question: '¿Qué órgano "se acelera" cuando estás enamorado/a?',
          options: ['El estómago', 'El corazón', 'Los pulmones', 'Todos'],
          correct: 4,
          hint: 'Mariposas incluidas 🦋',
        },
      ],
      thanksText: 'Por elegirme todos los días.',
    },
  },
  {
    id: 'boda',
    label: 'Casamiento y compromiso',
    keywords: [
      'casamiento',
      'boda',
      'compromiso',
      'propuesta',
      'recien casad',
      'luna de miel',
      'civil',
    ],
    category: 'Amor',
    emoji: '💍',
    cover: 'recipient',
    particles: 'heart',
    palettes: [
      {
        name: 'Champagne',
        primary: '#C8A26B',
        ink: '#2E2A26',
        accent: '#F4E3C3',
        card: '#EFE3D0',
        tone: 'dark',
      },
      {
        name: 'Blanco y oro',
        primary: '#B8925A',
        ink: '#26221E',
        accent: '#FFD98A',
        card: '#F7F1E8',
        tone: 'dark',
      },
    ],
    photos: [
      '1541250848049-b4f7141dca3f',
      '1519741497674-611481863552',
      '1511285560929-80b456fea0bc',
    ],
    listing: {
      title: 'Boxie de',
      subtitle: 'Para celebrar el "sí" más importante.',
      card: 'Un recuerdo digital para el día en que empezó el para siempre.',
      guideTitle: 'Para el Gran Día',
      guideText: 'Perfecta para novios, padrinos o para regalarle a la pareja recién casada.',
    },
    copy: {
      senderPrefix: 'Con todo el amor,',
      edition: 'WEDDING EDITION',
      thought: 'PARA SIEMPRE',
      message: 'Hoy empieza la mejor aventura.',
      dedicationHeading: 'Para los recién casados 💍',
      reasonsTitle: '10 Deseos',
      reasonsSubtitle: 'Para esta nueva etapa juntos...',
      reasons: [
        'Que nunca les falten las risas.',
        'Que cada día se elijan otra vez.',
        'Que viajen mucho y lejos.',
        'Que los domingos sean eternos.',
        'Que discutan poco y se abracen mucho.',
        'Que su casa esté llena de amigos.',
        'Que se cuiden siempre.',
        'Que se sigan sorprendiendo.',
        'Que construyan su propio mundo.',
        'Que sean felices, simplemente.',
      ],
      reasonsFinal: ['¡Vivan los novios! 🥂', 'Por muchos años más.'],
      coupons: [
        'Cena de Aniversario',
        'Noche de Hotel',
        'Brindis Sorpresa',
        'Fotos del Recuerdo',
        'Desayuno de Novios',
        'Escapada de Finde',
        'Baile Lento',
        'Deseo de Pareja',
      ],
      trivia: [
        {
          question: '¿En qué mano se usa tradicionalmente el anillo de casamiento en Argentina?',
          options: ['Derecha', 'Izquierda', 'Da igual', 'En las dos'],
          correct: 2,
          hint: 'La del corazón 💍',
        },
        {
          question: '¿Qué se tira al final de la fiesta para ver quién se casa después?',
          options: ['El zapato', 'El ramo', 'La liga', 'El velo'],
          correct: 2,
          hint: 'Tiene flores 💐',
        },
        {
          question: '¿Cómo se llaman las bodas de 25 años?',
          options: ['De oro', 'De plata', 'De cristal', 'De diamante'],
          correct: 2,
          hint: 'Brilla, pero no tanto como el oro ✨',
        },
      ],
      thanksTitle: 'SALUD',
      thanksText: 'Por el amor que nos une a todos.',
    },
  },
  {
    id: 'distancia',
    label: 'Amor a la distancia',
    keywords: ['distancia', 'extrano', 'lejos', 'kilometro', 'otro pais', 'reencuentro'],
    category: 'Amor',
    emoji: '🌍',
    cover: 'recipient',
    particles: 'heart',
    palettes: [
      {
        name: 'Cielo nocturno',
        primary: '#5B6CFF',
        ink: '#1E2140',
        accent: '#FFD166',
        card: '#5B6CFF',
        tone: 'light',
      },
    ],
    photos: ['1488646953014-85cb44e25828', '1516589178581-6cd7833ae3b2'],
    listing: {
      title: 'Boxie para',
      subtitle: 'Para acortar los kilómetros con un abrazo digital.',
      card: 'Porque la distancia no se nota cuando alguien piensa en vos.',
      guideTitle: 'Para Acercar',
      guideText:
        'Para parejas, familia o amigos que están lejos. Llega al instante, esté donde esté.',
    },
    copy: {
      senderPrefix: 'Desde lejos, con amor,',
      edition: 'LONG DISTANCE',
      thought: 'CERCANÍA',
      message: 'La distancia es solo un número.',
      reasonsTitle: '10 Razones',
      reasonsSubtitle: 'Por las que cada kilómetro vale la pena...',
      reasons: [
        'Porque te siento cerca aunque no estés.',
        'Por nuestras videollamadas eternas.',
        'Por cómo contás tu día.',
        'Porque me esperás.',
        'Por los mensajes de buenos días.',
        'Por cada cuenta regresiva.',
        'Porque lo nuestro vale el viaje.',
        'Por el próximo abrazo.',
        'Porque nada nos para.',
        'Porque sos mi lugar, estés donde estés.',
      ],
      coupons: [
        'Videollamada Larga',
        'Película Sincronizada',
        'Visita Sorpresa',
        'Cena Virtual',
        'Carta a Mano',
        'Playlist Compartida',
        'Abrazo Pendiente',
        'Plan del Reencuentro',
      ],
      fortunes: [
        'El próximo abrazo va a valer por todos los que faltaron.',
        'Cada día que pasa es un día menos para verse.',
        'Lo que es fuerte no se debilita con la distancia.',
        'Se viene un reencuentro que va a valer la espera.',
        'Estás más cerca de lo que el mapa dice.',
      ],
      thanksText: 'Por hacer que la distancia no importe.',
    },
  },
  {
    id: 'amistad',
    label: 'Amistad',
    keywords: [
      'amig',
      'amistad',
      '=bff',
      'best friend',
      'hermandad',
      '=compa',
      'grupo',
      'despedida de solter',
    ],
    category: 'Amistad',
    emoji: '👯',
    cover: 'friends',
    particles: 'friend',
    palettes: [
      {
        name: 'Lila amistad',
        primary: '#C893D7',
        ink: '#2A2433',
        accent: '#FFD700',
        card: '#C893D7',
        tone: 'light',
      },
      {
        name: 'Menta fresca',
        primary: '#2BB673',
        ink: '#1C2B24',
        accent: '#FFE066',
        card: '#A8E6CF',
        tone: 'dark',
      },
    ],
    photos: ['1529156069898-49953e39b3ac', '1522673607200-164d1b6ce486'],
    listing: {
      title: 'Boxie de',
      subtitle: 'Para esa persona que es familia elegida.',
      card: 'Celebrá la amistad con recuerdos, juegos y risas.',
      guideTitle: 'Para Celebrar',
      guideText: 'Ideal para tu mejor amigo/a, el grupo de siempre o un amigo que está lejos.',
    },
    copy: {
      senderPrefix: 'De:',
      edition: 'FRIENDSHIP EDITION',
      thought: 'AMISTAD',
      message: 'Porque los amigos son la familia que elegimos.',
      friendsQuote: '"La vida es mucho más divertida\ncuando estamos juntos."',
      reasons: [
        'Porque me bancás en todas.',
        'Por las risas hasta llorar.',
        'Por los secretos guardados.',
        'Porque sabés qué decir.',
        'Por las juntadas eternas.',
        'Porque sos sincero/a conmigo.',
        'Por los viajes que hicimos.',
        'Por los que nos quedan.',
        'Porque me conocés de memoria.',
        'Porque sos mi persona.',
      ],
      reasonsFinal: ['¡Amistad eterna! 🤞', 'Gracias por estar siempre.'],
      coupons: [
        'Juntada de Amigos',
        'Birra Invitada',
        'Tarde de Chismes',
        'Maratón de Series',
        'Road Trip',
        'Karaoke',
        'Asado Pagado',
        'Comodín de Favor',
      ],
      trivia: [
        {
          question: '¿Qué día se celebra el Día del Amigo en Argentina?',
          options: ['14 de febrero', '20 de julio', '21 de septiembre', '1 de mayo'],
          correct: 2,
          hint: 'Coincide con la llegada del hombre a la Luna 🌙',
        },
        {
          question: '¿Qué serie tiene la frase "I\'ll be there for you"?',
          options: ['Friends', 'How I Met Your Mother', 'Seinfeld', 'The Office'],
          correct: 1,
          hint: 'Central Perk ☕',
        },
        {
          question: '¿Cuántos amigos de verdad se dice que alcanzan?',
          options: ['Cien', 'Mil', 'Los que estén en las malas', 'Ninguno'],
          correct: 3,
          hint: 'La calidad le gana a la cantidad 😉',
        },
      ],
      thanksText: '¡Por muchas aventuras más juntos!',
    },
  },
  {
    id: 'cumpleanos',
    label: 'Cumpleaños',
    keywords: [
      'cumple',
      'birthday',
      'vuelta al sol',
      'quince',
      '15 anos',
      '18 anos',
      '30 anos',
      '40 anos',
      '50 anos',
    ],
    category: 'Cumpleaños',
    emoji: '🎂',
    cover: 'birthday',
    particles: 'bday-fest',
    palettes: [
      {
        name: 'Celeste fiesta',
        primary: '#73CFEE',
        ink: '#1F2A44',
        accent: '#FFD700',
        card: '#73CFEE',
        tone: 'dark',
      },
      {
        name: 'Confeti',
        primary: '#FF8A3D',
        ink: '#2A2433',
        accent: '#7C4DFF',
        card: '#FFB56B',
        tone: 'dark',
      },
    ],
    photos: ['1530103862676-de8c9debad1d', '1558636508-e0db3814bd1d', '1513151233558-d860c5398176'],
    listing: {
      title: 'Boxie de',
      subtitle: '¡Hacé que su día sea inolvidable, estés donde estés!',
      card: '¡Celebrá su día de manera especial con un detalle inolvidable!',
      guideTitle: 'Para Festejar',
      guideText: 'La fiesta digital: saludos, recuerdos y juegos para su día.',
    },
    copy: {
      senderPrefix: 'Con cariño,',
      edition: 'BIRTHDAY EDITION',
      thought: 'CELEBRACIÓN',
      message: 'Te merecés un día lleno de magia.',
      birthdayTitle: '¡FELIZ\nCUMPLE!',
      reasonsTitle: '10 Deseos',
      reasonsSubtitle: 'Para este nuevo año de vida...',
      reasons: [
        'Que te rías mucho.',
        'Que viajes a donde sueñes.',
        'Que te sobre salud.',
        'Que cumplas eso que venís pensando.',
        'Que te rodee gente linda.',
        'Que te animes a más.',
        'Que no te falten abrazos.',
        'Que disfrutes cada momento.',
        'Que brilles como siempre.',
        'Que sea tu mejor año.',
      ],
      reasonsFinal: ['¡Que se cumplan todos! 🎉', 'Feliz vuelta al sol.'],
      coupons: [
        'Torta Favorita',
        'Regalo Sorpresa',
        'Brindis Especial',
        'Organizo la Previa',
        'Fotógrafo Personal',
        'Día Libre',
        'Bajón Post-Fiesta',
        'Deseo de Cumple',
      ],
      trivia: [
        {
          question: '¿De qué país es originaria la canción "Feliz cumpleaños"?',
          options: ['Inglaterra', 'Estados Unidos', 'Francia', 'Argentina'],
          correct: 2,
          hint: 'La compusieron dos hermanas maestras 🇺🇸',
        },
        {
          question: '¿Qué se pide al soplar las velitas?',
          options: ['Un taxi', 'Tres deseos', 'Silencio', 'Más torta'],
          correct: 2,
          hint: 'No se cuentan, si no no se cumplen 🤫',
        },
        {
          question: '¿Cuántas vueltas al Sol das por año?',
          options: ['Media', 'Una', 'Dos', 'Doce'],
          correct: 2,
          hint: 'Por eso se festeja una vez 🌞',
        },
      ],
      thanksTitle: '¡FELIZ CUMPLE!',
      thanksText: 'Que este año sea el mejor de todos.',
    },
  },
  {
    id: 'madre',
    label: 'Día de la Madre',
    keywords: ['madre', 'mama', 'mami', 'vieja', 'mother'],
    category: 'Familia',
    emoji: '💐',
    cover: 'recipient',
    particles: 'circle',
    palettes: [
      {
        name: 'Lavanda',
        primary: '#A77BD6',
        ink: '#2D2340',
        accent: '#FFD1DC',
        card: '#D7C2F0',
        tone: 'dark',
      },
      {
        name: 'Flor de durazno',
        primary: '#F28C7A',
        ink: '#3B2522',
        accent: '#FFE0A3',
        card: '#FFD3C4',
        tone: 'dark',
      },
    ],
    photos: ['1476703993599-0035a21b17a9', '1490750967868-88aa4486c946'],
    listing: {
      title: 'Boxie para',
      subtitle: 'Para decirle gracias a la persona que te dio todo.',
      card: 'Un homenaje a mamá con recuerdos, fotos y mucho amor.',
      guideTitle: 'Para Mamá',
      guideText: 'Día de la Madre, su cumple o cualquier día para decirle cuánto la querés.',
    },
    copy: {
      coverLabel: 'Este regalo es para la mejor mamá...',
      senderPrefix: 'Con todo mi amor,',
      edition: 'MOM EDITION',
      thought: 'GRATITUD',
      message: 'Porque todo lo que soy empezó con vos.',
      dedicationHeading: 'Para vos, mamá 💐',
      reasons: [
        'Por tus abrazos que curan todo.',
        'Por cuidarme siempre.',
        'Por tus comidas únicas.',
        'Por enseñarme a ser fuerte.',
        'Porque siempre tenés un consejo.',
        'Por las veces que no dormiste por mí.',
        'Por tu risa.',
        'Por creer en mí.',
        'Porque sos mi ejemplo.',
        'Porque sos la mejor mamá del mundo.',
      ],
      reasonsFinal: ['¡Y un millón más! 💐', 'Te quiero, mamá.'],
      coupons: [
        'Desayuno en la Cama',
        'Día de Spa',
        'Almuerzo Juntas/os',
        'Lavo los Platos',
        'Paseo de Compras',
        'Tarde de Mates',
        'Abrazo Infinito',
        'Deseo de Mamá',
      ],
      trivia: [
        {
          question: '¿Qué mes se celebra el Día de la Madre en Argentina?',
          options: ['Mayo', 'Agosto', 'Octubre', 'Diciembre'],
          correct: 3,
          hint: 'El tercer domingo del mes de la primavera 🌷',
        },
        {
          question: '¿Qué frase dicen todas las mamás?',
          options: ['"Llevate un abrigo"', '"Comé algo"', '"Avisá cuando llegás"', 'Todas'],
          correct: 4,
          hint: 'Clásicos de todos los tiempos 😂',
        },
        {
          question: '¿Qué flor se regala tradicionalmente a las madres?',
          options: ['Clavel', 'Cactus', 'Girasol', 'Lirio'],
          correct: 1,
          hint: 'Es rosado o rojo 🌸',
        },
      ],
      thanksTitle: 'GRACIAS, MAMÁ',
      thanksText: 'Por ser mi lugar en el mundo.',
    },
  },
  {
    id: 'padre',
    label: 'Día del Padre',
    keywords: ['padre', 'papa', 'papi', 'viejo', 'father', 'dad'],
    category: 'Familia',
    emoji: '🧔',
    cover: 'recipient',
    particles: 'circle',
    palettes: [
      {
        name: 'Azul marino',
        primary: '#2F6FDB',
        ink: '#1B2233',
        accent: '#FFC247',
        card: '#2F6FDB',
        tone: 'light',
      },
      {
        name: 'Verde bosque',
        primary: '#2E8B57',
        ink: '#1B2B22',
        accent: '#F4D35E',
        card: '#9ED8B5',
        tone: 'dark',
      },
    ],
    photos: ['1511895426328-dc8714191300', '1543342384-1f1350e27861'],
    listing: {
      title: 'Boxie para',
      subtitle: 'Para el que siempre estuvo, aunque no lo diga.',
      card: 'Un regalo para papá con recuerdos, juegos y un gracias enorme.',
      guideTitle: 'Para Papá',
      guideText: 'Día del Padre, su cumple o para agradecerle todo lo que hace.',
    },
    copy: {
      coverLabel: 'Este regalo es para el mejor papá...',
      senderPrefix: 'Con cariño,',
      edition: 'DAD EDITION',
      thought: 'ORGULLO',
      message: 'Porque sos mi primer héroe.',
      dedicationHeading: 'Para vos, papá 💙',
      reasons: [
        'Por enseñarme a andar en bici.',
        'Por tus chistes malos.',
        'Por estar en cada partido.',
        'Por tus consejos (aunque no los pida).',
        'Por cuidarnos siempre.',
        'Por tu asado de los domingos.',
        'Por creer en mí.',
        'Por tu forma de ser.',
        'Porque sos mi ejemplo.',
        'Porque sos el mejor papá.',
      ],
      reasonsFinal: ['¡Y mil más! 💙', 'Te quiero, pa.'],
      coupons: [
        'Asado Pagado',
        'Partido Juntos',
        'Siesta Sin Interrupciones',
        'Lavado del Auto',
        'Tarde de Pesca',
        'Birra Compartida',
        'Control Remoto Libre',
        'Deseo de Papá',
      ],
      trivia: [
        {
          question: '¿Qué mes se celebra el Día del Padre en Argentina?',
          options: ['Marzo', 'Junio', 'Septiembre', 'Noviembre'],
          correct: 2,
          hint: 'El tercer domingo del mes del frío ❄️',
        },
        {
          question: '¿Cuál es el superpoder de todo papá?',
          options: ['Volar', 'Dormirse viendo tele', 'Leer mentes', 'Ser invisible'],
          correct: 2,
          hint: 'Aunque dice que estaba mirando 😴',
        },
        {
          question: '¿Qué frase es 100% de papá?',
          options: [
            '"Apagá la luz"',
            '"Preguntale a tu madre"',
            '"¿Quién tocó el termostato?"',
            'Todas',
          ],
          correct: 4,
          hint: 'Clásicos 😂',
        },
      ],
      thanksTitle: 'GRACIAS, PA',
      thanksText: 'Por enseñarme con el ejemplo.',
    },
  },
  {
    id: 'abuelos',
    label: 'Abuelos',
    keywords: ['abuel', 'nona', 'nono', 'yaya', '=tata', 'bisabuel'],
    category: 'Familia',
    emoji: '👵',
    cover: 'recipient',
    particles: 'circle',
    palettes: [
      {
        name: 'Terracota',
        primary: '#D9774B',
        ink: '#3A2A22',
        accent: '#FFD9A0',
        card: '#F3C9A8',
        tone: 'dark',
      },
    ],
    photos: ['1447005497901-b3e9ee359928', '1511895426328-dc8714191300'],
    listing: {
      title: 'Boxie para',
      subtitle: 'Para los abuelos que llenan la casa de historias.',
      card: 'Fotos, recuerdos y cariño para los abuelos, fácil de abrir.',
      guideTitle: 'Para los Abuelos',
      guideText: 'Letra grande, fotos y música: una experiencia simple para que la disfruten.',
    },
    copy: {
      coverLabel: 'Este regalo es para vos, abu...',
      senderPrefix: 'Con todo el amor de tus nietos,',
      edition: 'FAMILY EDITION',
      thought: 'RAÍCES',
      message: 'Porque tus historias son nuestro tesoro.',
      reasons: [
        'Por tus historias de antes.',
        'Por tus comidas de domingo.',
        'Por consentirnos siempre.',
        'Por tus consejos sabios.',
        'Por las tardes en tu casa.',
        'Por tu paciencia.',
        'Por enseñarnos lo importante.',
        'Por tu risa.',
        'Por ser el centro de la familia.',
        'Porque te queremos muchísimo.',
      ],
      coupons: [
        'Almuerzo en Familia',
        'Visita Sorpresa',
        'Tarde de Fotos Viejas',
        'Paseo Juntos',
        'Llamada Larga',
        'Mates y Charla',
        'Receta Compartida',
        'Abrazo de Nieto',
      ],
      thanksText: 'Por ser la raíz de todo lo lindo.',
    },
  },
  {
    id: 'bebe',
    label: 'Bebé y nacimiento',
    keywords: [
      'bebe',
      'nacimiento',
      'baby',
      'embaraz',
      'nacio',
      'recien nacid',
      'bautismo',
      'maternidad',
      'paternidad',
    ],
    category: 'Familia',
    emoji: '👶',
    cover: 'recipient',
    particles: 'circle',
    palettes: [
      {
        name: 'Celeste bebé',
        primary: '#7FB8E6',
        ink: '#23324A',
        accent: '#FFE39F',
        card: '#CFE6F7',
        tone: 'dark',
      },
      {
        name: 'Rosa talco',
        primary: '#EFA3B8',
        ink: '#3A2531',
        accent: '#FFF1B8',
        card: '#F9D9E2',
        tone: 'dark',
      },
    ],
    photos: ['1566004100631-35d015d6a491', '1519689680058-324335c77eba', '1543342384-1f1350e27861'],
    listing: {
      title: 'Boxie de',
      subtitle: 'Para darle la bienvenida al miembro más chiquito.',
      card: 'Un recuerdo digital para celebrar una nueva vida.',
      guideTitle: 'Para Dar la Bienvenida',
      guideText: 'Para los nuevos papás, un baby shower o el primer añito.',
    },
    copy: {
      coverLabel: 'Este regalo es para darte la bienvenida...',
      senderPrefix: 'Con muchísimo amor,',
      edition: 'BABY EDITION',
      thought: 'NUEVA VIDA',
      message: 'Llegaste y todo cambió para mejor.',
      reasonsTitle: '10 Deseos',
      reasonsSubtitle: 'Para esta personita que recién llega...',
      reasons: [
        'Que crezcas feliz.',
        'Que te sobren abrazos.',
        'Que tengas mucha salud.',
        'Que seas curioso/a.',
        'Que juegues mucho.',
        'Que te rodee el amor.',
        'Que duermas bien (y tus papás también).',
        'Que descubras el mundo.',
        'Que seas vos mismo/a.',
        'Que seas muy, muy feliz.',
      ],
      coupons: [
        'Niñera por una Noche',
        'Comida Hecha',
        'Siesta para los Papás',
        'Paseo con el Cochecito',
        'Sesión de Fotos',
        'Pañales de Emergencia',
        'Visita con Regalo',
        'Deseo de Bienvenida',
      ],
      thanksTitle: 'BIENVENIDO/A',
      thanksText: 'Al mundo, a la familia, a nuestros corazones.',
    },
  },
  {
    id: 'ninos',
    label: 'Día del Niño',
    keywords: ['nino', 'nina', 'infancia', 'chicos', 'hijo', 'hija', 'sobrin', 'dia del nino'],
    category: 'Familia',
    emoji: '🧸',
    cover: 'birthday',
    particles: 'bday-fest',
    palettes: [
      {
        name: 'Arcoíris',
        primary: '#FF6B6B',
        ink: '#2A2433',
        accent: '#4ECDC4',
        card: '#FFE66D',
        tone: 'dark',
      },
    ],
    photos: ['1503454537195-1dcabb73ffb9', '1502086223501-7ea6ecd79368'],
    listing: {
      title: 'Boxie para',
      subtitle: 'Una aventura digital llena de juegos para los más chicos.',
      card: 'Juegos, sorpresas y colores para el Día del Niño.',
      guideTitle: 'Para Jugar',
      guideText: 'Para hijos, sobrinos o ahijados: trivia, tragamonedas y vales para canjear.',
    },
    copy: {
      coverLabel: '¡Una sorpresa para vos!',
      edition: 'KIDS EDITION',
      thought: 'DIVERSIÓN',
      message: '¡Hoy es tu día, a jugar!',
      birthdayTitle: '¡FELIZ DÍA\nDEL NIÑO!',
      reasonsTitle: '10 Cosas',
      reasonsSubtitle: 'Que nos encantan de vos...',
      reasons: [
        'Tu imaginación.',
        'Tus preguntas.',
        'Tus dibujos.',
        'Cómo te reís.',
        'Tus ocurrencias.',
        'Que sos valiente.',
        'Que compartís.',
        'Tus abrazos de oso.',
        'Tus ganas de aprender.',
        'Que sos único/a.',
      ],
      coupons: [
        'Helado Doble',
        'Tarde en la Plaza',
        'Pijamada',
        'Película con Pochoclos',
        'Cocinar Juntos',
        'Un Juguete',
        'Acostarse Tarde',
        'Día de Juegos',
      ],
      trivia: [
        {
          question: '¿Qué animal es el más grande del mundo?',
          options: ['Elefante', 'Ballena azul', 'Jirafa', 'Tiburón'],
          correct: 2,
          hint: 'Vive en el mar 🐳',
        },
        {
          question: '¿Cuántas patas tiene una araña?',
          options: ['Seis', 'Ocho', 'Diez', 'Cuatro'],
          correct: 2,
          hint: 'Más que un perro, menos que un ciempiés 🕷️',
        },
        {
          question: '¿Qué planeta tiene anillos?',
          options: ['Marte', 'Saturno', 'Venus', 'Mercurio'],
          correct: 2,
          hint: 'Parece que lleva un aro 🪐',
        },
      ],
      thanksTitle: '¡A SEGUIR JUGANDO!',
      thanksText: 'Te queremos muchísimo.',
    },
  },
  {
    id: 'graduacion',
    label: 'Graduación y logros',
    keywords: [
      'gradu',
      'egres',
      'recibid',
      'titulo',
      'universidad',
      'facultad',
      'secundario',
      'logro',
      'tesis',
      'examen',
      'aprobad',
    ],
    category: 'Logros',
    emoji: '🎓',
    cover: 'recipient',
    particles: 'bday-fest',
    palettes: [
      {
        name: 'Azul y oro',
        primary: '#274690',
        ink: '#171E33',
        accent: '#F5B700',
        card: '#274690',
        tone: 'light',
      },
      {
        name: 'Bordó académico',
        primary: '#8C1C3B',
        ink: '#2B1520',
        accent: '#F2C14E',
        card: '#8C1C3B',
        tone: 'light',
      },
    ],
    photos: ['1627556704302-624286467c65', '1513151233558-d860c5398176'],
    listing: {
      title: 'Boxie de',
      subtitle: 'Para celebrar el esfuerzo de todos estos años.',
      card: 'Celebrá su título, su egreso o ese logro que tanto costó.',
      guideTitle: 'Para Celebrar Logros',
      guideText:
        'Egresos, títulos, un examen difícil o un ascenso: todo esfuerzo merece su festejo.',
    },
    copy: {
      coverLabel: 'Este regalo es para quien lo logró...',
      senderPrefix: 'Con mucho orgullo,',
      edition: 'GRADUATION EDITION',
      thought: 'ESFUERZO',
      message: 'Lo soñaste, lo trabajaste, lo lograste.',
      dedicationHeading: '¡Lo lograste! 🎓',
      reasonsTitle: '10 Razones',
      reasonsSubtitle: 'Para estar orgullosos de vos...',
      reasons: [
        'Por cada noche de estudio.',
        'Por no rendirte.',
        'Por tu disciplina.',
        'Por levantarte después de cada bocha.',
        'Por tu curiosidad.',
        'Por ayudar a tus compañeros.',
        'Por creer en vos.',
        'Por todo lo que aprendiste.',
        'Por lo que vas a lograr.',
        'Porque te lo merecés.',
      ],
      reasonsFinal: ['¡Felicitaciones! 🎉', 'Esto recién empieza.'],
      coupons: [
        'Festejo Pagado',
        'Cena de Egresado/a',
        'Día Sin Alarmas',
        'Brindis Oficial',
        'Viaje de Descanso',
        'Sesión de Fotos',
        'Regalo Sorpresa',
        'Deseo Cumplido',
      ],
      trivia: [
        {
          question: '¿Qué se tira al aire al graduarse?',
          options: ['Los apuntes', 'El birrete', 'El título', 'Los zapatos'],
          correct: 2,
          hint: 'Va en la cabeza 🎓',
        },
        {
          question: '¿Cuál es la universidad más antigua de Argentina?',
          options: ['UBA', 'UNLP', 'Universidad de Córdoba', 'UTN'],
          correct: 3,
          hint: 'Se fundó en 1613 🏛️',
        },
        {
          question: '¿Qué es lo primero que se hace al recibirse?',
          options: ['Dormir', 'Festejar', 'Llamar a mamá', 'Todas'],
          correct: 4,
          hint: 'No hay respuesta incorrecta 😄',
        },
      ],
      thanksTitle: '¡FELICITACIONES!',
      thanksText: 'Por todo lo que viene.',
    },
  },
  {
    id: 'jubilacion',
    label: 'Jubilación',
    keywords: ['jubila', 'retiro', 'nueva etapa', 'ultimo dia de trabajo'],
    category: 'Logros',
    emoji: '🏖️',
    cover: 'recipient',
    particles: 'circle',
    palettes: [
      {
        name: 'Playa',
        primary: '#1FA2C6',
        ink: '#16303A',
        accent: '#FFD27D',
        card: '#9FE0F0',
        tone: 'dark',
      },
    ],
    photos: ['1507525428034-b723cf961d3e', '1476514525535-07fb3b4ae5f1'],
    listing: {
      title: 'Boxie de',
      subtitle: 'Para celebrar una carrera y todo lo que viene.',
      card: 'Un homenaje a años de trabajo y un brindis por la nueva etapa.',
      guideTitle: 'Para la Nueva Etapa',
      guideText: 'Para despedir a un compañero o celebrar a alguien de la familia que se jubila.',
    },
    copy: {
      edition: 'NEW CHAPTER',
      thought: 'NUEVA ETAPA',
      message: 'Ahora sí: tiempo para vos.',
      reasonsTitle: '10 Planes',
      reasonsSubtitle: 'Para esta nueva vida...',
      reasons: [
        'Dormir sin alarma.',
        'Viajar sin apuro.',
        'Aprender algo nuevo.',
        'Leer esos libros pendientes.',
        'Más tiempo con la familia.',
        'Cuidar las plantas.',
        'Caminar al sol.',
        'Cocinar sin reloj.',
        'Hacer lo que tengas ganas.',
        'Disfrutar lo que construiste.',
      ],
      coupons: [
        'Viaje Soñado',
        'Clase de Algo Nuevo',
        'Almuerzo Largo',
        'Día de Pesca',
        'Tarde de Lectura',
        'Paseo por la Costa',
        'Asado de Despedida',
        'Deseo Libre',
      ],
      thanksText: 'Por tantos años de dedicación.',
    },
  },
  {
    id: 'navidad',
    label: 'Navidad y fiestas',
    keywords: [
      'navidad',
      'christmas',
      'fiestas',
      'ano nuevo',
      'reyes',
      'noche buena',
      'nochebuena',
      'papa noel',
      'fin de ano',
    ],
    category: 'Fechas especiales',
    emoji: '🎄',
    cover: 'recipient',
    particles: 'circle',
    palettes: [
      {
        name: 'Rojo navidad',
        primary: '#C8102E',
        ink: '#1F2A22',
        accent: '#F4C542',
        card: '#C8102E',
        tone: 'light',
      },
      {
        name: 'Pino',
        primary: '#1E7B4F',
        ink: '#15251C',
        accent: '#F4C542',
        card: '#1E7B4F',
        tone: 'light',
      },
    ],
    photos: ['1482517967863-00e15c9b44be', '1512389142860-9c449e58a543', '1543589077-47d81606c1bf'],
    listing: {
      title: 'Boxie de',
      subtitle: 'El regalo que llega a tiempo, sin colas ni envíos.',
      card: 'Un regalo navideño que llega al instante, esté donde esté.',
      guideTitle: 'Para las Fiestas',
      guideText: 'Navidad, Año Nuevo o Reyes: ideal para regalar a distancia y a último momento.',
    },
    copy: {
      coverLabel: 'Papá Noel dejó esto para...',
      senderPrefix: '¡Felices fiestas!',
      greeting: '¡JO JO JO!',
      edition: 'CHRISTMAS EDITION',
      thought: 'MAGIA',
      message: 'Que la magia de estas fiestas te acompañe todo el año.',
      dedicationHeading: 'Carta navideña 🎄',
      reasonsTitle: '10 Deseos',
      reasonsSubtitle: 'Para este año que empieza...',
      reasons: [
        'Salud para vos y los tuyos.',
        'Mesas largas y llenas.',
        'Muchos viajes.',
        'Abrazos de los que reinician.',
        'Proyectos que se cumplan.',
        'Tiempo para lo importante.',
        'Risas de sobremesa.',
        'Paz en el corazón.',
        'Sorpresas lindas.',
        'Un año inolvidable.',
      ],
      reasonsFinal: ['¡Felices fiestas! 🎄', 'Y un año nuevo increíble.'],
      coupons: [
        'Brindis a las 12',
        'Vitel Toné Casero',
        'Pan Dulce Compartido',
        'Película Navideña',
        'Armado del Arbolito',
        'Regalo Sorpresa',
        'Paseo de Luces',
        'Deseo de Año Nuevo',
      ],
      trivia: [
        {
          question: '¿Qué día llegan los Reyes Magos?',
          options: ['24 de diciembre', '31 de diciembre', '6 de enero', '1 de enero'],
          correct: 3,
          hint: 'Traen regalos a los chicos que dejan los zapatos 👟',
        },
        {
          question: '¿Cuántos renos tiene Papá Noel (sin contar a Rodolfo)?',
          options: ['Cuatro', 'Seis', 'Ocho', 'Diez'],
          correct: 3,
          hint: 'Rodolfo es el noveno 🦌',
        },
        {
          question: '¿Qué plato no puede faltar en una Navidad argentina?',
          options: ['Vitel toné', 'Sushi', 'Guiso', 'Ñoquis'],
          correct: 1,
          hint: 'Lleva salsa de atún 🐟',
        },
      ],
      thanksTitle: '¡FELICES FIESTAS!',
      thanksText: 'Que se vengan cosas lindas.',
    },
  },
  {
    id: 'halloween',
    label: 'Halloween',
    keywords: ['halloween', 'terror', 'miedo', 'bruja', 'fantasma', 'calabaza'],
    category: 'Fechas especiales',
    emoji: '🎃',
    cover: 'friends',
    particles: 'circle',
    palettes: [
      {
        name: 'Calabaza',
        primary: '#FF7518',
        ink: '#1A1423',
        accent: '#9D4EDD',
        card: '#2B1D3A',
        tone: 'light',
      },
    ],
    photos: ['1509557965875-b88c97052f0e', '1513151233558-d860c5398176'],
    listing: {
      title: 'Boxie de',
      subtitle: 'Un regalo terroríficamente divertido.',
      card: 'Sustos, dulces y juegos para una noche de Halloween distinta.',
      guideTitle: 'Para Asustar (con Amor)',
      guideText: 'Para los fans del terror, una fiesta temática o una broma con cariño.',
    },
    copy: {
      senderPrefix: 'Muajaja,',
      greeting: '¡BUU!',
      edition: 'HALLOWEEN EDITION',
      thought: 'DULCE O TRUCO',
      message: 'Esta noche los sustos son de regalo.',
      friendsQuote: '"Dulce o truco…\nhoy te toca un regalo."',
      coupons: [
        'Maratón de Terror',
        'Bolsa de Dulces',
        'Disfraz Compartido',
        'Fiesta de Disfraces',
        'Cuento de Miedo',
        'Pochoclos a Oscuras',
        'Susto Garantizado',
        'Deseo Embrujado',
      ],
      thanksTitle: '¡FELIZ HALLOWEEN!',
      thanksText: 'Dulces sueños… si podés 👻',
    },
  },
  {
    id: 'mascotas',
    label: 'Mascotas',
    keywords: ['mascota', 'perr', 'gat', 'cachorr', 'michi', 'firulais', '=pet', '=dog', '=cat'],
    category: 'Mascotas',
    emoji: '🐾',
    cover: 'friends',
    particles: 'circle',
    palettes: [
      {
        name: 'Hueso y caramelo',
        primary: '#E08E45',
        ink: '#2E2319',
        accent: '#8FD694',
        card: '#F6D6AD',
        tone: 'dark',
      },
      {
        name: 'Verde parque',
        primary: '#4CAF50',
        ink: '#1D2B1E',
        accent: '#FFCA3A',
        card: '#B8E0B9',
        tone: 'dark',
      },
    ],
    photos: ['1543466835-00a7907e9de1', '1514888286974-6c03e2ca1dba', '1517849845537-4d257902454a'],
    listing: {
      title: 'Boxie de',
      subtitle: 'Para los que aman a sus peludos tanto como vos.',
      card: 'Un regalo para amantes de las mascotas, con su foto y mucho amor.',
      guideTitle: 'Para Amantes de Mascotas',
      guideText:
        'Su cumple, su adopción o un regalo para quien tiene al mejor perro o gato del mundo.',
    },
    copy: {
      senderPrefix: 'Con amor (y pelos),',
      edition: 'PET EDITION',
      thought: 'AMOR PELUDO',
      message: 'Porque quien tiene una mascota tiene un amor incondicional.',
      friendsQuote: '"Hogar es donde\nalguien mueve la cola."',
      reasons: [
        'Porque te recibe como si no te viera hace años.',
        'Por sus siestas eternas.',
        'Por su cara de "no fui yo".',
        'Porque te cuida.',
        'Por sus locuras.',
        'Porque te entiende sin palabras.',
        'Por los paseos.',
        'Por su amor sin condiciones.',
        'Porque te hace reír todos los días.',
        'Porque es parte de la familia.',
      ],
      reasonsTitle: '10 Razones',
      reasonsSubtitle: 'Por las que tu mascota es la mejor...',
      coupons: [
        'Paseo Largo',
        'Juguete Nuevo',
        'Baño y Peinado',
        'Sesión de Fotos',
        'Día de Parque',
        'Premio Rico',
        'Cuidado por un Finde',
        'Siesta Compartida',
      ],
      trivia: [
        {
          question: '¿Cuántas horas por día duerme un gato, aproximadamente?',
          options: ['6', '10', '15', '20'],
          correct: 3,
          hint: 'Más de la mitad del día 😴',
        },
        {
          question: '¿Qué sentido tienen más desarrollado los perros?',
          options: ['La vista', 'El olfato', 'El gusto', 'El tacto'],
          correct: 2,
          hint: 'Por eso huelen todo 👃',
        },
        {
          question: '¿Por qué los gatos ronronean?',
          options: ['Solo de hambre', 'Para comunicarse', 'Porque roncan', 'Para dormir'],
          correct: 2,
          hint: 'Casi siempre es un "te quiero" 😻',
        },
      ],
      fortunes: [
        'Se vienen muchos paseos y más mimos.',
        'Alguien de cuatro patas te espera en la puerta.',
        'El amor más sincero viene con bigotes (o con cola).',
        'Hoy toca premio… para vos y tu peludo.',
        'Tu mascota piensa que sos la mejor persona del mundo. Tiene razón.',
      ],
      thanksTitle: '¡GUAU!',
      thanksText: 'Gracias por tanto amor peludo 🐾',
    },
  },
  {
    id: 'viajes',
    label: 'Viajes y despedidas',
    keywords: [
      'viaj',
      'vacacion',
      'despedida',
      'mochiler',
      'intercambio',
      'aventura',
      'mudanza',
      'me voy',
      'buen viaje',
    ],
    category: 'Viajes',
    emoji: '✈️',
    cover: 'recipient',
    particles: 'circle',
    palettes: [
      {
        name: 'Turquesa',
        primary: '#00A6A6',
        ink: '#12302F',
        accent: '#FFB703',
        card: '#8FE3E0',
        tone: 'dark',
      },
    ],
    photos: ['1488646953014-85cb44e25828', '1476514525535-07fb3b4ae5f1'],
    listing: {
      title: 'Boxie de',
      subtitle: 'Para despedir a quien se va a vivir una aventura.',
      card: 'Un regalo para llevarse de viaje: recuerdos, música y buenos deseos.',
      guideTitle: 'Para Viajeros',
      guideText: 'Despedidas, intercambios, mudanzas o el viaje soñado.',
    },
    copy: {
      senderPrefix: '¡Buen viaje!',
      edition: 'TRAVEL EDITION',
      thought: 'AVENTURA',
      message: 'El mundo es tuyo: salí a descubrirlo.',
      reasonsTitle: '10 Deseos',
      reasonsSubtitle: 'Para esta aventura...',
      reasons: [
        'Que conozcas lugares increíbles.',
        'Que pruebes comidas nuevas.',
        'Que hagas amigos en todos lados.',
        'Que te pierdas y te encuentres.',
        'Que saques mil fotos.',
        'Que te animes a todo.',
        'Que vuelvas con mil historias.',
        'Que nunca te falte nada.',
        'Que disfrutes cada día.',
        'Que vuelvas pronto (o que te visitemos).',
      ],
      coupons: [
        'Videollamada Semanal',
        'Visita Garantizada',
        'Paquete desde Casa',
        'Mate por Cámara',
        'Guía Turístico',
        'Bienvenida al Volver',
        'Álbum de Fotos',
        'Deseo Viajero',
      ],
      thanksTitle: '¡BUEN VIAJE!',
      thanksText: 'Te vamos a extrañar.',
    },
  },
  {
    id: 'gamer',
    label: 'Gamers',
    keywords: [
      'gamer',
      'videojuego',
      'gaming',
      'counter',
      'cs2',
      'cs go',
      'fortnite',
      'minecraft',
      'league',
      '=lol',
      'playstation',
      'nintendo',
      'xbox',
      'valorant',
      'fifa',
    ],
    category: 'Hobbies',
    emoji: '🎮',
    cover: 'recipient',
    particles: 'circle',
    palettes: [
      {
        name: 'Neón',
        primary: '#7C3AED',
        ink: '#0F0B1F',
        accent: '#22D3EE',
        card: '#1E1340',
        tone: 'light',
      },
      {
        name: 'Verde terminal',
        primary: '#16A34A',
        ink: '#0B1410',
        accent: '#FACC15',
        card: '#0F2A1A',
        tone: 'light',
      },
    ],
    photos: ['1542751371-adc38448a05e', '1511512578047-dfb367046420'],
    listing: {
      title: 'Boxie',
      subtitle: 'Para el jugador o la jugadora que tenés al lado.',
      card: 'Level up: un regalo con trivia, jackpot y logros desbloqueados.',
      guideTitle: 'Para Gamers',
      guideText: 'Para fans de los videojuegos: logros, trivia gamer y mucho estilo neón.',
    },
    copy: {
      coverLabel: 'Nuevo logro desbloqueado para...',
      senderPrefix: 'GG,',
      greeting: 'PLAYER 1',
      edition: 'GAMER EDITION',
      thought: 'LEVEL UP',
      message: 'Desbloqueaste un regalo legendario.',
      reasonsTitle: '10 Logros',
      reasonsSubtitle: 'Que desbloqueaste en mi vida...',
      reasons: [
        'Mejor compañero/a de equipo.',
        'Maestro/a del respawn.',
        'Rey/Reina de las noches largas.',
        'Nunca rage quit (bueno, casi).',
        'Carry emocional.',
        'Speedrun de hacerme reír.',
        'Easter egg favorito.',
        'Siempre con buen ping.',
        'Legendario/a en todo.',
        'Player 2 para siempre.',
      ],
      reasonsFinal: ['ACHIEVEMENT UNLOCKED 🏆', 'GG WP.'],
      coupons: [
        'Partida Juntos',
        'Juego Nuevo',
        'Noche de LAN',
        'Pizza y Vicio',
        'Skin a Elección',
        'Sin Preguntar la Hora',
        'Torneo Casero',
        'Continue Extra',
      ],
      trivia: [
        {
          question: '¿Cómo se llama el fontanero más famoso de los videojuegos?',
          options: ['Luigi', 'Mario', 'Wario', 'Toad'],
          correct: 2,
          hint: 'Tiene bigote y gorra roja 🍄',
        },
        {
          question: '¿En qué juego se construye con bloques y se esquiva a los creepers?',
          options: ['Roblox', 'Fortnite', 'Minecraft', 'Terraria'],
          correct: 3,
          hint: 'Todo es cúbico ⛏️',
        },
        {
          question: '¿Qué significa "GG"?',
          options: ['Gran Gol', 'Good Game', 'Game Go', 'Gracias Gente'],
          correct: 2,
          hint: 'Se dice al terminar la partida 🤝',
        },
      ],
      fortunes: [
        'Tu próxima partida viene con victoria asegurada.',
        'Se acerca un drop legendario.',
        'Hoy tenés crítico en todo.',
        'El boss final no sabe lo que le espera.',
        'Tu racha recién empieza.',
      ],
      thanksTitle: 'GAME OVER',
      thanksText: '¿Jugamos otra?',
    },
  },
  {
    id: 'futbol',
    label: 'Fútbol y deporte',
    keywords: [
      'futbol',
      'deport',
      'hincha',
      'mundial',
      'boca',
      'river',
      'racing',
      'independiente',
      'san lorenzo',
      'seleccion',
      'messi',
      '=club',
      'running',
      '=gym',
      'tenis',
      'basquet',
      'rugby',
    ],
    category: 'Hobbies',
    emoji: '⚽',
    cover: 'recipient',
    particles: 'circle',
    palettes: [
      {
        name: 'Albiceleste',
        primary: '#5BA4E6',
        ink: '#14233A',
        accent: '#FFD23F',
        card: '#CDE6FA',
        tone: 'dark',
      },
      {
        name: 'Cancha',
        primary: '#2E9E4F',
        ink: '#132A1B',
        accent: '#FFFFFF',
        card: '#2E9E4F',
        tone: 'light',
      },
    ],
    photos: ['1574629810360-7efbbe195018', '1579952363873-27f3bade9f55'],
    listing: {
      title: 'Boxie',
      subtitle: 'Para el que vive cada partido como una final.',
      card: 'Un regalo con trivia futbolera, cábalas y mucho aguante.',
      guideTitle: 'Para Hinchas',
      guideText: 'Para fanáticos del fútbol o de cualquier deporte: pasión, trivia y cábalas.',
    },
    copy: {
      coverLabel: 'Este golazo es para...',
      senderPrefix: 'Con aguante,',
      greeting: '¡GOOOL!',
      edition: 'FOOTBALL EDITION',
      thought: 'PASIÓN',
      message: 'Porque la vida es mejor con pasión.',
      reasonsTitle: '10 Razones',
      reasonsSubtitle: 'Por las que sos crack...',
      reasons: [
        'Por tu aguante incondicional.',
        'Por tus cábalas.',
        'Por gritar los goles como nadie.',
        'Por tu garra.',
        'Por jugar en equipo.',
        'Porque nunca abandonás.',
        'Por tus análisis post-partido.',
        'Por las previas compartidas.',
        'Por tu pasión.',
        'Porque sos titular en mi vida.',
      ],
      reasonsFinal: ['¡Dale campeón! 🏆', 'Sos de primera.'],
      coupons: [
        'Entrada a la Cancha',
        'Picadito con Amigos',
        'Camiseta Nueva',
        'Asado Post-Partido',
        'Partido en Pantalla Grande',
        'Previa Pagada',
        'Cábala Respetada',
        'Deseo de Campeón',
      ],
      trivia: [
        {
          question: '¿Cuántas Copas del Mundo ganó la Selección Argentina?',
          options: ['Una', 'Dos', 'Tres', 'Cuatro'],
          correct: 3,
          hint: '1978, 1986 y 2022 ⭐⭐⭐',
        },
        {
          question: '¿Cuántos jugadores tiene un equipo de fútbol en cancha?',
          options: ['9', '10', '11', '12'],
          correct: 3,
          hint: 'Arquero incluido 🧤',
        },
        {
          question: '¿Qué número usaba Maradona en la Selección?',
          options: ['7', '9', '10', '11'],
          correct: 3,
          hint: 'El número de los cracks 🔟',
        },
      ],
      thanksTitle: '¡GRACIAS, CRACK!',
      thanksText: 'Sos de primera división.',
    },
  },
  {
    id: 'musica',
    label: 'Música',
    keywords: [
      'music',
      'rock',
      'banda',
      'concierto',
      'recital',
      'cantante',
      'guitarr',
      '=trap',
      'cumbia',
      '=pop',
      '=dj',
    ],
    category: 'Hobbies',
    emoji: '🎸',
    cover: 'recipient',
    particles: 'circle',
    palettes: [
      {
        name: 'Escenario',
        primary: '#E63946',
        ink: '#14111A',
        accent: '#F1FAEE',
        card: '#1D1A24',
        tone: 'light',
      },
    ],
    photos: [
      '1511379938547-c1f69419868d',
      '1470225620780-dba8ba36b745',
      '1493225255756-d9584f8606e9',
    ],
    listing: {
      title: 'Boxie',
      subtitle: 'Para quien vive con los auriculares puestos.',
      card: 'Canciones, playlists y recuerdos para melómanos.',
      guideTitle: 'Para Melómanos',
      guideText: 'Con su canción, playlists y recuerdos de recitales.',
    },
    copy: {
      senderPrefix: 'Con buena música,',
      edition: 'MUSIC EDITION',
      thought: 'RITMO',
      message: 'Tu vida merece su propia banda sonora.',
      reasonsTitle: '10 Temas',
      reasonsSubtitle: 'Que me recuerdan a vos...',
      coupons: [
        'Entrada a un Recital',
        'Vinilo Favorito',
        'Karaoke',
        'Playlist Personalizada',
        'Clase de Instrumento',
        'Noche de Covers',
        'Road Trip con Música',
        'Deseo Musical',
      ],
      trivia: [
        {
          question: '¿Qué banda argentina grabó "De música ligera"?',
          options: ['Los Redondos', 'Soda Stereo', 'Los Enanitos Verdes', 'Virus'],
          correct: 2,
          hint: 'Cerati 🎸',
        },
        {
          question: '¿Cuántas cuerdas tiene una guitarra clásica?',
          options: ['Cuatro', 'Cinco', 'Seis', 'Siete'],
          correct: 3,
          hint: 'Mi-La-Re-Sol-Si-Mi 🎶',
        },
        {
          question: '¿Qué instrumento marca el ritmo en una banda?',
          options: ['La flauta', 'La batería', 'El violín', 'El piano'],
          correct: 2,
          hint: 'Pum-pum-tss 🥁',
        },
      ],
      thanksTitle: 'FIN DEL SHOW',
      thanksText: '¡Otra, otra!',
    },
  },
  {
    id: 'docentes',
    label: 'Docentes',
    keywords: [
      'docente',
      'maestr',
      'profe',
      'seno',
      'escuela',
      'jardin',
      'dia del maestro',
      'educador',
    ],
    category: 'Agradecimiento',
    emoji: '🍎',
    cover: 'recipient',
    particles: 'circle',
    palettes: [
      {
        name: 'Pizarrón',
        primary: '#2F855A',
        ink: '#1A2A22',
        accent: '#F6E05E',
        card: '#C6F6D5',
        tone: 'dark',
      },
    ],
    photos: ['1503676260728-1c00da094a0b', '1580582932707-520aed937b7b'],
    listing: {
      title: 'Boxie para',
      subtitle: 'Para agradecer a quien enseña con el corazón.',
      card: 'Un gracias colectivo para la seño, el profe o la maestra.',
      guideTitle: 'Para Docentes',
      guideText: 'Día del Maestro, fin de año o una despedida: el regalo que arma todo el grado.',
    },
    copy: {
      coverLabel: 'Este regalo es para una gran docente...',
      senderPrefix: 'Con cariño, tus alumnos,',
      edition: 'TEACHER EDITION',
      thought: 'ENSEÑAR',
      message: 'Lo que enseñaste nos va a acompañar siempre.',
      reasonsTitle: '10 Gracias',
      reasonsSubtitle: 'Por todo lo que nos diste...',
      reasons: [
        'Por tu paciencia infinita.',
        'Por explicar mil veces.',
        'Por hacernos reír.',
        'Por creer en nosotros.',
        'Por las clases distintas.',
        'Por escucharnos.',
        'Por tu dedicación.',
        'Por enseñarnos a pensar.',
        'Por los valores.',
        'Por ser inolvidable.',
      ],
      coupons: [
        'Mate con Facturas',
        'Clase sin Tarea',
        'Aplauso de Pie',
        'Día de Descanso',
        'Carta del Grado',
        'Flores en el Escritorio',
        'Silencio Absoluto',
        'Deseo Cumplido',
      ],
      thanksTitle: 'GRACIAS, PROFE',
      thanksText: 'Por dejar huella.',
    },
  },
  {
    id: 'gracias',
    label: 'Agradecimiento',
    keywords: [
      'gracias',
      'agradec',
      'jefe',
      'jefa',
      'equipo',
      'compañer',
      'trabajo',
      'oficina',
      'cliente',
      'colega',
      'reconocimiento',
    ],
    category: 'Agradecimiento',
    emoji: '🙌',
    cover: 'recipient',
    particles: 'circle',
    palettes: [
      {
        name: 'Mostaza',
        primary: '#E0A100',
        ink: '#2A2418',
        accent: '#3A86FF',
        card: '#FBE3A1',
        tone: 'dark',
      },
    ],
    photos: ['1522071820081-009f0129c71c', '1495474472287-4d71bcdd2085'],
    listing: {
      title: 'Boxie de',
      subtitle: 'Para decir gracias de una forma que se recuerda.',
      card: 'Un gracias distinto para un compañero, un jefe o un cliente.',
      guideTitle: 'Para Agradecer',
      guideText: 'Para equipos de trabajo, clientes o alguien que te dio una mano enorme.',
    },
    copy: {
      senderPrefix: 'Con gratitud,',
      edition: 'THANK YOU EDITION',
      thought: 'GRATITUD',
      message: 'Hay personas que hacen todo más fácil. Vos sos una.',
      reasonsTitle: '10 Gracias',
      reasonsSubtitle: 'Por lo que aportás todos los días...',
      reasons: [
        'Por tu buena onda.',
        'Por dar una mano siempre.',
        'Por tu compromiso.',
        'Por tus ideas.',
        'Por resolver lo imposible.',
        'Por escuchar.',
        'Por el café compartido.',
        'Por hacer equipo.',
        'Por tu paciencia.',
        'Por ser como sos.',
      ],
      coupons: [
        'Café Invitado',
        'Almuerzo Pagado',
        'Tarde Libre',
        'Reunión Cancelada',
        'After Office',
        'Te Cubro un Día',
        'Snack Sorpresa',
        'Comodín de Favor',
      ],
      thanksTitle: 'GRACIAS',
      thanksText: 'Por hacer la diferencia.',
    },
  },
  {
    id: 'animo',
    label: 'Ánimo y recuperación',
    keywords: [
      'animo',
      'recuper',
      'mejoria',
      'fuerza',
      'salud',
      'hospital',
      'operacion',
      'sanar',
      'aguanta',
    ],
    category: 'Ánimo',
    emoji: '🌻',
    cover: 'recipient',
    particles: 'circle',
    palettes: [
      {
        name: 'Girasol',
        primary: '#F2B705',
        ink: '#2B2410',
        accent: '#6BCB77',
        card: '#FFE58A',
        tone: 'dark',
      },
    ],
    photos: ['1470509037663-253afd7f0f51', '1490750967868-88aa4486c946'],
    listing: {
      title: 'Boxie de',
      subtitle: 'Un abrazo digital para los días difíciles.',
      card: 'Para acompañar, dar fuerza y sacar una sonrisa.',
      guideTitle: 'Para Dar Fuerza',
      guideText:
        'Para alguien que está pasando un momento difícil, una recuperación o una mala racha.',
    },
    copy: {
      senderPrefix: 'Siempre con vos,',
      edition: 'GOOD VIBES',
      thought: 'FUERZA',
      message: 'No estás solo/a: acá estamos.',
      reasonsTitle: '10 Razones',
      reasonsSubtitle: 'Para seguir adelante...',
      reasons: [
        'Porque sos más fuerte de lo que creés.',
        'Porque ya superaste cosas difíciles.',
        'Porque te queremos.',
        'Porque vienen días lindos.',
        'Por todo lo que te falta vivir.',
        'Porque tu risa hace falta.',
        'Porque no estás solo/a.',
        'Porque cada día es un paso.',
        'Porque sos inspiración.',
        'Porque esto también va a pasar.',
      ],
      reasonsFinal: ['¡Fuerza! 🌻', 'Estamos con vos.'],
      coupons: [
        'Visita con Mimos',
        'Comida Casera',
        'Película y Manta',
        'Paseo al Sol',
        'Llamada cuando Quieras',
        'Mandado Hecho',
        'Tarde de Risas',
        'Abrazo Largo',
      ],
      fortunes: [
        'Los días lindos están más cerca de lo que parece.',
        'Tu fuerza inspira a más gente de la que imaginás.',
        'Un paso a la vez también es avanzar.',
        'Lo difícil pasa; lo que aprendés, queda.',
        'Se viene una buena noticia.',
      ],
      thanksTitle: 'FUERZA',
      thanksText: 'Estamos con vos, siempre.',
    },
  },
  {
    id: 'perdon',
    label: 'Perdón y reconciliación',
    keywords: ['perdon', 'disculpa', 'reconcilia', 'lo siento', 'arrepent'],
    category: 'Amor',
    emoji: '🕊️',
    cover: 'recipient',
    particles: 'heart',
    palettes: [
      {
        name: 'Rosa empolvado',
        primary: '#D87093',
        ink: '#2F2029',
        accent: '#FFE4B5',
        card: '#F7D6E0',
        tone: 'dark',
      },
    ],
    photos: ['1518895949257-7621c3c786d7', '1516589178581-6cd7833ae3b2'],
    listing: {
      title: 'Boxie de',
      subtitle: 'Para cuando un "perdón" necesita algo más.',
      card: 'Para pedir perdón con el corazón y volver a empezar.',
      guideTitle: 'Para Reconciliar',
      guideText: 'Para arreglar las cosas con alguien importante, con palabras sinceras.',
    },
    copy: {
      senderPrefix: 'Con el corazón en la mano,',
      edition: 'SORRY EDITION',
      thought: 'SINCERIDAD',
      message: 'A veces las palabras no alcanzan. Por eso esto.',
      dedicationHeading: 'Te debo esto 🕊️',
      reasonsTitle: '10 Razones',
      reasonsSubtitle: 'Por las que vale la pena volver a intentarlo...',
      reasons: [
        'Porque me importás.',
        'Porque aprendí.',
        'Por todo lo lindo que tenemos.',
        'Porque te extraño.',
        'Porque quiero hacerlo mejor.',
        'Porque lo nuestro vale.',
        'Por tu forma de perdonar.',
        'Porque quiero escucharte.',
        'Porque no quiero perderte.',
        'Porque te quiero.',
      ],
      coupons: [
        'Charla Sincera',
        'Cena de Paz',
        'Te Escucho sin Interrumpir',
        'Abrazo de Reconciliación',
        'Salida Sorpresa',
        'Sí a Todo por un Día',
        'Carta a Mano',
        'Empezar de Nuevo',
      ],
      thanksTitle: 'GRACIAS',
      thanksText: 'Por leer hasta acá.',
    },
  },
]

/** Para lo que no coincide con ninguna ocasión. */
export const GENERAL_SPEC: ArchetypeSpec = {
  id: 'general',
  label: 'Celebración',
  keywords: [],
  category: 'Celebraciones',
  emoji: '🎁',
  cover: 'recipient',
  particles: 'circle',
  palettes: [
    ROSE,
    {
      name: 'Violeta Boxie',
      primary: '#8E6FE0',
      ink: '#231C38',
      accent: '#FFD166',
      card: '#D9CCF7',
      tone: 'dark',
    },
    {
      name: 'Cielo',
      primary: '#3A9BDC',
      ink: '#17293A',
      accent: '#FFC857',
      card: '#BFE2F7',
      tone: 'dark',
    },
    {
      name: 'Menta',
      primary: '#20A77B',
      ink: '#15291F',
      accent: '#FFD23F',
      card: '#B7ECD8',
      tone: 'dark',
    },
  ],
  photos: ['1549465220-1a8b9238cd48', '1513885535751-8b9238bd345a'],
  listing: {
    subtitle: 'Un regalo digital para celebrar lo que quieras.',
    card: 'Fotos, música, juegos y una dedicatoria para una ocasión especial.',
  },
  copy: {},
}

export function resolveArchetype(spec: ArchetypeSpec): Archetype {
  return {
    ...spec,
    listing: {
      title: 'Boxie de',
      features: [],
      guideTitle: `Para ${spec.label}`,
      guideText: spec.listing.card,
      ...spec.listing,
    },
    copy: { ...BASE_COPY, ...(spec.copy as Partial<Archetype['copy']>) },
  }
}
